sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rsgomide/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsgomide/docker-react npm run test